using System;
using UnityEngine;

namespace SandJamTest
{
    // Values recovered from the original game's ScriptableObjects (ColorDataSO, NewFeatureConfig,
    // NewBoosterConfig, EasyHardLevelConfig). Generated by the editor importer into Resources/OriginalConfig.
    public static class OriginalConfig
    {
        [Serializable] public sealed class ColorEntry { public int type; public Color init, final, dark, render; }
        [Serializable] public sealed class Intro { public int index, type, showLevel; public string info, gif; }
        [Serializable] sealed class Colors { public ColorEntry[] colors; }
        [Serializable] sealed class Intros { public Intro[] features, boosters; }
        [Serializable] sealed class Difficulty { public int[] easy, hard; }

        static ColorEntry[] colors;
        static Intros intros;
        static Difficulty difficulty;

        static T Load<T>(string name) where T : class
        {
            var asset = Resources.Load<TextAsset>("OriginalConfig/" + name);
            return asset ? JsonUtility.FromJson<T>(asset.text) : null;
        }

        public static ColorEntry Color(int type)
        {
            if (colors == null) { var c = Load<Colors>("colors"); colors = c != null && c.colors != null ? c.colors : new ColorEntry[0]; }
            return Array.Find(colors, e => e.type == type);
        }

        public static Intro[] Features { get { EnsureIntros(); return intros.features ?? new Intro[0]; } }
        public static Intro[] Boosters { get { EnsureIntros(); return intros.boosters ?? new Intro[0]; } }
        static void EnsureIntros() { if (intros == null) intros = Load<Intros>("intros") ?? new Intros(); }

        static void EnsureDifficulty() { if (difficulty == null) difficulty = Load<Difficulty>("difficulty") ?? new Difficulty { easy = new int[0], hard = new int[0] }; }
        public static bool IsHard(int level) { EnsureDifficulty(); return Array.IndexOf(difficulty.hard, level) >= 0; }
        public static bool IsEasy(int level) { EnsureDifficulty(); return Array.IndexOf(difficulty.easy, level) >= 0; }

        // Booster type ids in NewBoosterConfig: 1 flare (rocket), 2 swap, 0 select any.
        public static int BoosterUnlockLevel(string action)
        {
            int type = action == "rocket" ? 1 : action == "swap" ? 2 : action == "select" ? 0 : -1;
            var entry = Array.Find(Boosters, b => b.type == type);
            return entry != null ? entry.showLevel : 1;
        }
    }
}
